# Generated by Django 4.1.2 on 2024-06-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElComilon', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(db_column='idComuna', primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(db_column='idRegion', primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=40)),
                ('numero_direccion', models.IntegerField(max_length=6)),
                ('contraseña', models.CharField(max_length=30)),
                ('id_comuna', models.ForeignKey(db_column='idComuna', on_delete=django.db.models.deletion.CASCADE, to='ElComilon.comuna')),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='ElComilon.genero')),
                ('id_region', models.ForeignKey(db_column='idRegion', on_delete=django.db.models.deletion.CASCADE, to='ElComilon.region')),
            ],
        ),
    ]
