# Generated by Django 5.0 on 2024-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElComilon', '0007_alter_usuario_numero_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_region',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='dato', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
