# Generated by Django 4.1.2 on 2024-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElComilon', '0008_remove_usuario_id_comuna_remove_usuario_id_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
