# Generated by Django 5.0.6 on 2024-07-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElComilon', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('correo_cliente', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('total_compra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='ElComilon.compra')),
            ],
        ),
    ]
